name: kindle-reading-tracker
on:
  workflow_dispatch:
jobs:
  track-reading:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup git config
        run: |
          git config user.name "GitHub Action Bot"
          git config user.email "weijianduan0302@gmail.com"
      - name: empty commit for tracking reading
        run: git commit --allow-empty -m "track reading, and keep going!"
      - name: push code to main
        run: git push origin HEAD:main
